drop table if exists participants cascade;
drop table if exists competition cascade;
drop table if exists stage cascade;
drop table if exists news cascade;
drop table if exists partners cascade;
drop table if exists events cascade;
drop table if exists location cascade;
drop table if exists direction cascade;
drop table if exists users cascade;
drop table if exists media cascade;
drop table if exists region cascade;
drop table if exists country cascade;
drop table if exists city cascade;

create table country (
    id integer not null generated by default as identity,
    name varchar not null unique,
    constraint country_pk primary key (id)
);

create table region (
    id integer not null generated by default as identity,
    name varchar not null unique,
    country_id integer not null,
    constraint region_pk primary key (id),
    constraint region_fk foreign key (country_id) references country(id)
);

create table media (
    id bigint not null generated by default as identity,
    name varchar not null unique,
    link varchar not null,
    stream_date_time timestamp without time zone not null,
    published_date timestamp without time zone not null,
    constraint photo_pk primary key (id)
);

create table users (
    id bigint not null generated by default as identity,
    surname varchar not null,
    name varchar not null,
    patronymic varchar not null,
    type varchar not null,
    email varchar not null unique,
    password varchar not null,
    birthday timestamp without time zone,
    country_id integer not null,
    region_id integer not null,
    city varchar not null,
    link varchar not null,
    phone varchar not null,
    gender varchar not null,
    nationality varchar not null,
    photo_id integer not null,
    portfolio varchar not null,
    description varchar not null,                 
    constraint users_pk primary key (id),
    constraint users_fk foreign key (country_id) references country(id),
    constraint users_fk1 foreign key (region_id) references region(id),
    constraint users_fk2 foreign key (photo_id) references photo(id)
);

create table direction (
    id integer not null,
    name varchar(20)   not null,
    constraint direction_pk primary key (id)
);

create table location (
    id bigint not null generated by default as identity,
    lon float,
    constraint location_pk primary key (id)
);

create table events (
    id bigint not null generated by default as identity,
    name varchar not null,
    type varchar not null,
    direction_id integer not null,
    date timestamp without time zone not null,
    description varchar not null,
    location integer not null,
    time varchar not null,
    constraint events_pk primary key (id)
);

create table partners (
    id bigint not null generated by default as identity,
    icon_id bigint not null,
    name varchar not null,
    type varchar not null,
    description varchar not null,
    link varchar not null,
    constraint partners_pk primary key (id),
    constraint partners_fk foreign key (icon_id) references photo(id)
);

create table news (
    id bigint not null generated by default as identity,
    photo_id integer not null,
    name varchar not null,
    description varchar not null,
    published_date timestamp without time zone,
    constraint news_pk primary key (id),
    constraint news_fk foreign key (photo_id) references photo(id)
);

create table stage (
    id integer not null generated by default as identity,
    name varchar not null,
    start_date timestamp without time zone,
    end_date timestamp without time zone,
    status varchar not null,
    constraint stage_pk primary key (id)
);

create table competition (
    id bigint not null generated by default as identity,
    name varchar not null,
    description varchar not null,
    direction_id integer not null,
    stage_id integer not null,
    constraint competition_pk primary key (id),
    constraint competition_fk foreign key (direction_id) references direction(id),
    constraint competition_fk1 foreign key (stage_id) references stage(id)
);

create table participants (
    id bigint not null generated by default as identity,
    user_id integer not null,
    competition_id integer not null,
    direction_id integer not null,
    user_status varchar not null,
    constraint participants_pk primary key (id),
    constraint participants_fk foreign key (user_id) references users(id),
    constraint participants_fk1 foreign key (competition_id) references competition(id),
    constraint participants_fk2 foreign key (direction_id) references participants(id)
);