drop table if exists region cascade;
drop table if exists country cascade;
drop table if exists role cascade;
drop table if exists streams cascade;
drop table if exists users_likes cascade;
drop table if exists user_role cascade;
drop table if exists posts cascade;
drop table if exists comments cascade;
drop table if exists evaluating cascade;
drop table if exists competition_participants cascade;
drop table if exists event_participants cascade;
drop table if exists competition cascade;
drop table if exists stage cascade;
drop table if exists news cascade;
drop table if exists partners cascade;
drop table if exists events cascade;
drop table if exists location cascade;
drop table if exists direction cascade;
drop table if exists users cascade;
drop table if exists admin cascade;
drop table if exists files_info cascade;
drop table if exists events_directions cascade;
drop table if exists directions cascade;
drop table if exists admin_links cascade;
drop table if exists user_links cascade;

create table country
(
    id   bigint  not null generated by default as identity,
    name varchar not null,
    constraint country_pk primary key (id)
);

create table region
(
    id      bigint  not null generated by default as identity,
    name    varchar not null,
    country_id bigint  not null,
    constraint region_pk primary key (id),
    constraint region_fk foreign key (country_id) references country (id)
);

create table files_info
(
    id               bigint  not null generated by default as identity,
    file_name        varchar not null,
    file_size        bigint  not null,
    file_key         varchar not null,
    file_path        varchar not null,
    file_upload_date timestamp,
    constraint files_info_pk primary key (id)
);

create table users
(
    id               bigint  not null generated by default as identity,
    user_surname     varchar not null,
    user_name        varchar not null,
    user_patronymic  varchar not null,
    type             varchar not null,
    user_email       varchar not null unique,
    user_password    varchar not null,
    user_birthday    timestamp without time zone,
    country_id       integer not null,
    region_id        integer not null,
    city             varchar not null,
    user_link        varchar not null,
    user_phone       varchar not null,
    user_gender      varchar not null,
    user_nationality varchar not null,
    photo_id         integer not null,
    portfolio        varchar not null,
    description      varchar not null,
    constraint users_pk primary key (id),
    constraint users_fk foreign key (country_id) references country (id),
    constraint users_fk1 foreign key (region_id) references region (id),
    constraint users_fk2 foreign key (photo_id) references files_info (id)
);

create table direction
(
    id   integer     not null,
    name varchar(20) not null unique,
    constraint direction_pk primary key (id)
);

create table location
(
    id  bigint not null generated by default as identity,
    lon float,
    lat float,
    constraint location_pk primary key (id)
);

create table posts
(
    id           bigint  not null generated by default as identity,
    file_id      bigint  not null,
    description  varchar not null,
    likes        bigint,
    dislikes     bigint,
    author_id    bigint  not null,
    direction    varchar not null,
    created_date timestamp,
    updated_date timestamp,
    constraint posts_pk primary key (id),
    constraint posts_fk foreign key (file_id) references files_info (id),
    constraint posts_fk1 foreign key (author_id) references users (id)
);

create table events
(
    id           bigint    not null generated by default as identity,
    name         varchar   not null,
    type         varchar   not null,
    direction_id integer   not null,
    date         timestamp not null,
    description  varchar   not null,
    location_id  bigint,
    time         varchar   not null,
    constraint events_pk primary key (id),
    constraint events_fk foreign key (location_id) references location (id)
);

create table partners
(
    id          bigint  not null generated by default as identity,
    icon_id     bigint  not null,
    name        varchar not null,
    type        varchar not null,
    description varchar not null,
    link        varchar not null,
    constraint partners_pk primary key (id),
    constraint partners_fk foreign key (icon_id) references files_info (id)
);

create table news
(
    id             bigint  not null generated by default as identity,
    photo_id       integer not null,
    name           varchar not null,
    description    varchar not null,
    published_date timestamp,
    constraint news_pk primary key (id),
    constraint news_fk foreign key (photo_id) references files_info (id)
);

create table stage
(
    id         integer not null generated by default as identity,
    name       varchar not null,
    start_date timestamp,
    end_date   timestamp,
    status     varchar not null,
    constraint stage_pk primary key (id)
);

create table competition
(
    id           bigint  not null generated by default as identity,
    name         varchar not null,
    description  varchar not null,
    direction_id integer not null,
    stage_id     integer not null,
    constraint competition_pk primary key (id),
    constraint competition_fk foreign key (direction_id) references direction (id),
    constraint competition_fk1 foreign key (stage_id) references stage (id)
);

create table competition_participants
(
    id             bigint  not null generated by default as identity,
    user_id        integer not null,
    competition_id integer not null,
    direction      varchar not null,
    constraint competition_participants_pk primary key (id),
    constraint competition_participants_fk foreign key (user_id) references users (id),
    constraint competition_participants_fk1 foreign key (competition_id) references competition (id),
    constraint competition_participants_fk2 foreign key (direction) references direction (name)
);

create table event_participants
(
    id       bigint  not null generated by default as identity,
    user_id  integer not null,
    event_id integer not null,
    constraint event_participants_pk primary key (id),
    constraint event_participants_fk foreign key (user_id) references users (id),
    constraint event_participants_fk1 foreign key (event_id) references events (id)
);

create table comments
(
    id           bigint    not null generated by default as identity,
    text         varchar,
    post_id      bigint    not null,
    author_id    bigint    not null,
    created_date timestamp not null,
    updated_date timestamp not null,
    constraint comments_pk primary key (id),
    constraint comments_fk foreign key (post_id) references posts (id),
    constraint comments_fk1 foreign key (author_id) references users (id)
);

create table evaluating
(
    id             bigint  not null generated by default as identity,
    competition_id bigint  not null,
    stage_id       integer not null,
    participant_id bigint  not null,
    expert_id      bigint  not null,
    points         float,
    constraint evaluating_pk primary key (id),
    constraint evaluating_fk foreign key (competition_id) references competition (id),
    constraint evaluating_fk1 foreign key (stage_id) references stage (id),
    constraint evaluating_fk2 foreign key (participant_id) references competition_participants (id),
    constraint evaluating_fk3 foreign key (expert_id) references users (id)
);

create table users_likes
(
    id      bigint  not null generated by default as identity,
    post_id bigint  not null,
    user_id bigint  not null,
    type    varchar not null,
    constraint users_likes_pk primary key (id),
    constraint users_likes_fk foreign key (post_id) references posts (id),
    constraint users_likes_fk1 foreign key (user_id) references users (id)
);

create table streams
(
    id               bigint  not null generated by default as identity,
    name             varchar not null,
    link             varchar not null,
    stream_date_time timestamp,
    published_date   timestamp,
    constraint streams_pk primary key (id)
);

create table admin
(
    id       bigint  not null generated by default as identity,
    surname  varchar not null,
    name     varchar not null,
    email    varchar not null unique,
    password varchar not null,
    link     varchar not null,
    phone    varchar not null,
    photo_id integer not null,
    constraint admin_pk primary key (id),
    constraint admin_fk foreign key (photo_id) references files_info (id)
);

create table directions
(
    id   bigint  not null generated by default as identity,
    name varchar not null,
    constraint directions_pk primary key (id)
);

create table events_directions
(
    id           bigint not null generated by default as identity,
    event_id     bigint not null,
    direction_id bigint not null,
    constraint events_directions_pk primary key (id),
    constraint events_directions_fk foreign key (event_id) references events (id),
    constraint events_directions_fk1 foreign key (direction_id) references directions (id)
);

create table admin_links
(
    id       bigint  not null generated by default as identity,
    admin_id bigint  not null,
    link     varchar not null,
    constraint admin_links_pk primary key (id),
    constraint admin_links_fk foreign key (admin_id) references admin (id)
);

create table user_links
(
    id      bigint  not null generated by default as identity,
    user_id bigint  not null,
    link    varchar not null,
    constraint user_links_pk primary key (id),
    constraint user_links_fk foreign key (user_id) references users (id)
);